algoritmo "Soma dos Números"

// Função: Lopal (Lógica de Programação)

//F9 ( executar o código)

//Autor:Lorena Oliveira
//Data: 13/04/2026
var
//Declaração Variáveis

notaUM,notaDOIS,notaTRES,valorFinal:real

inicio
// inicio dos dados

escreva ("coloque o primeiro valor da nota: ")
leia (notaUM)

escreva ("coloque o segundo valor da nota: ")
leia (notaDOIS)

escreva ("coloque o terceiro valor da nota: ")
leia (notaTRES)

//realizar a soma da média final
valorFinal<- notaUm + notaDOIS + notaTRES /3

escreval ("o valor final dessa soma", valorFinal)

fimalgoritmo




