algoritmo " Convertendo °C para °F"
// Disciplina : Lopal (Logica de Programação)

//F9 (executar o código)

// Autor : Lorena Oliveira
// Data : 13/04/2026

var
// Declaração de variáveis
grausC,valorF: real

inicio
// Entrada de dados
   escreva ("digite a temperatura em °C: ")
   leia (grausC)
//Converter para °F
valorF <- 9 * grausC / 5 + 32   [

escreval ("o valor convertido para °F é igual a ",valorF)


fimalgoritmo
