algoritmo " Índice de Massa Corpórea "
// Disciplina: Lopal ( Logica de Programação)
//F9 (executar o código)

// Autor :Lorena Oliveira

// Data : 13/04/2026


var
// Declaração de variáveis
peso,altura,valorFinal: real


inicio
// Entrada de Dados
   escreva ("escreva o valor do peso: ")
   leia (peso)
   
   escreva("escreva o valor da altura: ")
   leia (altura)
   
// O valor do IMC
valorFinal<- peso/ (altura * altura)

escreval ( " o valor da IMC ", valorFinal )
fimalgoritmo
