algoritmo "As somas dos números"
// Disciplina: Lopal (logística de programação)

//F9 (executar o código)

//Autor:Lorena Oliveira
//Data:07/04/2026

var
//Declaraçaõ de variáveis

     numeroUm, numeroDois, Soma: real

inicio
// Entrada de Dados
   escreva ("escreva o primeiro Valor: ")
   leia(numeroUM)
   
   escreva ("escreva o segundo valor: ")
   leia (numeroDois)
   

// O Valor da soma aplicada

   Soma<- numeroUm + numeroDois

   escreval ("o valor final dessa soma", Soma)

fimalgoritmo
