algoritmo "Area do Trapézio"
// Disciplina : Lopal (Logica de Programação)

//F9 (executar o código)

// Autor :Lorena Oliveira

// Data : 13/04/2026

var
 //Declaração de variáveis
 baseMaior,baseMenor,altura,valorFinal: real
 
inicio
// Entrada de Dados
   escreva ("escreva o valor da base Maior:")
   leia (baseMaior)
   
   escreva ("escreva o valor da base Menor: ")
   leia (baseMenor)
   
   escreva ("escreva o valor da altura: ")
   leia (altura)
   
   // O Valor da Area multiplicada, e  dividido por 2
   valorFinal<-(baseMaior+baseMenor)* altura /2

    escreval ( " o valor da soma da area", valorFinal)
fimalgoritmo
